### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку linked_lists Серебро Андрей

### ISSUE THREAD

**Issue by Aspirisha** [Aspirisha/au-linux-kernel-spring-2016#1]
https://github.com/Aspirisha/au-linux-kernel-spring-2016/commit/8aeea855eef3ed951dcbdd145c2aa72d4b8d7ece

**Comment by eabatalov** [comment]
You have many errors so 40% for the task.
See comments in commit.

**Comment by Aspirisha** [comment]
Ой! А сегодня ещё можно пофиксить? Я вчера прошляпил :( 10.03.2016, 14:21, "Eugene Batalov" notifications@github.com:Closed #1.—Reply to this email directly or view it on GitHub.   -- Regards, Andrei Serebrotel. +79111758381

**Comment by eabatalov** [comment]
Здравствуйте. У нас в курсе все ДЗ сдаются по одному разу.

**Comment by Aspirisha** [comment]
Евгений, понял вас! Впредь буду аккуратнее =) 11.03.2016, 21:05, "Eugene Batalov" notifications@github.com:Здравствуйте. У нас в курсе все ДЗ сдаются по одному разу.—Reply to this email directly or view it on GitHub.   -- Regards, Andrei Serebrotel. +79111758381
