### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку virt_mem_max Серебро Андрей

### ISSUE THREAD

**Issue by Aspirisha** [Aspirisha/au-linux-kernel-spring-2016#3]
https://github.com/Aspirisha/au-linux-kernel-spring-2016/commit/40215e361a6a73ebec28ba00cf3ac4bf05411a7a

**Comment by eabatalov** [comment]
Almost ok. But you don't reach the maximal continuous address range allocation so I do a small reduction of your points.
75 points out of 100
