### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку mutex Серебро Андрей

### ISSUE THREAD

**Issue by Aspirisha** [Aspirisha/au-linux-kernel-spring-2016#6]
1e84297fdc7d715d0a33181401246741917c3597
Что-то бенчмарки не особенно радуют :/

**Comment by eabatalov** [comment]
Soooo... At least you've tried it. And this is very good.
45% for your work.

**Comment by eabatalov** [comment]
And you have Linux kernel credit automatically. No doubt.
